### ISSUE TITLE
Can't access web-server routes while captive portal is active

### ISSUE THREAD

**Issue by charliesneath** [resin-io-projects/resin-wifi-connect-api#1]
Taking this example for a test drive. I'm able to get the captive portal login to pop-up, but I'm not able to access anything served by the web server that's listening on port 80 (specifically while the login modal is open).

I'm unfamiliar with how captive portals provide access to anything beyond the captive portal UI, so this might be expected behavior.

That said, is it possible to access routes provided by the web server (e.g. `/`) while connected to the portal? How can one access those custom routes while still providing the SSID and PSK info to the `wifi-connect` server?

Or is the web server only available to capture POST requests submitted from the captive portal UI?

Thank you for the guidance!

**Comment by charliesneath** [comment]
Found the issue: was using the IP address from the device's LAN, not wifi-connect.

**Comment by majorz** [comment]
Closing since issue was solved.
