### ISSUE TITLE
WiFi Connect Push Error

### ISSUE THREAD

**Issue by andrewjaykeller** [resin-io-projects/resin-wifi-connect-api#2]
We tried to push this project to our device and got the error:

```bash
[wifi-connect]  Successfully built 83bb85f7301a
[Info]          Uploading images
[Success]       Successfully uploaded images
[Error]         Some services failed to build:
[Error]           Service: web-app
[Error]             Error: manifest for resin/artik533s-python:3.6.4-20180420 not found
[Error]         Not deploying release.
```

**Comment by majorz** [comment]
@andrewjaykeller looks like the container image specified does not exist for Artik. You may try out a different one for now. I recommend the new base images (the `balenalib` ones).

**Comment by andrewjaykeller** [comment]
We did try with balenalib but still had no success, any ideas?

**Comment by majorz** [comment]
This should be resolved now in the latest update. Please let me know if you still experience any issues with this.

**Comment by KuhlTime** [comment]
I got (almost) the same error as Andrew when pushing the project. 
```
manifest for balenalib/raspberry-pi-python:3.7.2-20190327 not found: manifest unknown: manifest unknown
```
I could get it to work by setting the image to the latest version of python:
```
FROM balenalib/%%RESIN_MACHINE_NAME%%-python:3-latest
```
